import { Question, UserProfile, ErrorEntry } from "./types";

export const MOCK_QUESTIONS: Question[] = [

  // ================================================================
  //  言语理解与表达 (yanyu) — 15 题
  // ================================================================

  {
    id: "yanyu-001", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "逻辑填空", difficulty: 2,
    question: '在经济全球化的今天，任何国家都不可能独善其身地发展，国际合作已成为不可逆转的趋势。',
    options: [
      { key: "A", text: '闭关锁国' },
      { key: "B", text: '独善其身' },
      { key: "C", text: '自力更生' },
      { key: "D", text: '孤立无援' },
    ],
    answer: "B",
    explanation: '独善其身指在污浊的环境中能不受干扰地坚持自己的美好节操，也指只顾自身不管他人。此处语境为国家层面的发展，独善其身最贴合语境。',
    knowledgePoints: ["言语理解", "逻辑填空", "词语辨析"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-002", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "逻辑填空", difficulty: 2,
    question: '科学研究需要一丝不苟的精神，任何急功近利的投机取巧都不可能产生真正的成果。',
    options: [
      { key: "A", text: '一丝不苟；急功近利' },
      { key: "B", text: '精益求精；半途而废' },
      { key: "C", text: '锲而不舍；好高骛远' },
      { key: "D", text: '实事求是；沽名钓誉' },
    ],
    answer: "A",
    explanation: '一丝不苟形容做事认真细致，急功近利指急于求成贪图眼前利益，两者形成对比，最符合语境。',
    knowledgePoints: ["言语理解", "逻辑填空", "成语辨析"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-003", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "片段阅读", difficulty: 3,
    question: '人工智能的发展正在深刻改变着教育领域。一方面，AI可以为学生提供个性化的学习方案；另一方面，AI也能帮助教师从繁琐的重复性工作中解放出来。然而，过度依赖AI也可能导致学生自主思考能力的下降。这段文字主要讨论的是：',
    options: [
      { key: "A", text: 'AI在教育领域的应用前景' },
      { key: "B", text: 'AI对教育带来的机遇与挑战' },
      { key: "C", text: 'AI如何改变教学方式' },
      { key: "D", text: '过度依赖AI的潜在风险' },
    ],
    answer: "B",
    explanation: '文段结构为一方面另一方面然而，既讲了AI在教育中的优势也讲了风险，核心观点是机遇与挑战并存。',
    knowledgePoints: ["言语理解", "片段阅读", "主旨概括"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-004", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "片段阅读", difficulty: 2,
    question: '有人说，汉字是中华文明的基因。从甲骨文到楷书，汉字的形态虽然发生了巨大变化，但其表意的本质始终未变。正是这种延续性，使得今天的中国人仍能读懂两千多年前的文献。这段文字意在说明：',
    options: [
      { key: "A", text: '汉字的演变历程' },
      { key: "B", text: '汉字的表意功能' },
      { key: "C", text: '汉字对文明传承的作用' },
      { key: "D", text: '古今文献的可读性' },
    ],
    answer: "C",
    explanation: '文段用基因比喻汉字，强调其在中华文明中的核心作用，末句落脚点是汉字维系了文明的延续。',
    knowledgePoints: ["言语理解", "片段阅读", "意图推断"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-005", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "细节判断", difficulty: 2,
    question: '根据原文判断：目前全球约有10亿人面临水资源短缺。联合国预测到2050年这一数字可能翻倍。应对水资源危机需要从开源和节流两方面入手。以下哪项与原文不符？',
    options: [
      { key: "A", text: '目前全球约10亿人面临水资源短缺' },
      { key: "B", text: '到2050年水资源短缺人数可能达到20亿' },
      { key: "C", text: '海水淡化属于节流措施' },
      { key: "D", text: '提高用水效率属于节流' },
    ],
    answer: "C",
    explanation: '原文明确说开发海水淡化等新技术属于开源，而C选项说属于节流，与原文矛盾。',
    knowledgePoints: ["言语理解", "细节判断", "文段对比"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-006", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "逻辑填空", difficulty: 3,
    question: '数字经济时代，数据已成为生产要素。然而，数据的价值不可估量，唯有经过有效的采集、清洗、分析和应用，才能真正释放出来。',
    options: [
      { key: "A", text: '无可置疑；体现' },
      { key: "B", text: '不言自明；转化' },
      { key: "C", text: '不可估量；释放' },
      { key: "D", text: '显而易见；挖掘' },
    ],
    answer: "C",
    explanation: '不可估量形容数据价值巨大难以衡量，释放搭配价值恰当。',
    knowledgePoints: ["言语理解", "逻辑填空", "语境分析"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-007", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "主旨概括", difficulty: 3,
    question: '基层治理是国家治理的基石。长期面临上面千条线下面一根针的困境。近年来各地积极探索减负增效，推动基层治理从管理走向服务。对这段文字概括最准确的是：',
    options: [
      { key: "A", text: '基层治理面临的困难' },
      { key: "B", text: '数字化转型对基层治理的重要性' },
      { key: "C", text: '基层减负增效的探索与转型' },
      { key: "D", text: '从管理到服务是基层治理的必经之路' },
    ],
    answer: "C",
    explanation: '文段先说困境，再说积极探索减负增效，最后指出方向，C最全面。',
    knowledgePoints: ["言语理解", "片段阅读", "主旨概括"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-008", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "意图推断", difficulty: 3,
    question: '近年来国潮文化兴起，故宫文创年销售额突破10亿元，汉服爱好者突破千万。这些现象表明，年轻一代并非不热爱传统文化，而是需要找到与传统文化对话的新方式。这段文字意在强调：',
    options: [
      { key: "A", text: '国潮文化的商业价值' },
      { key: "B", text: '传统文化需要创新表达方式' },
      { key: "C", text: '年轻人是传统文化的主要受众' },
      { key: "D", text: '故宫文创的成功经验' },
    ],
    answer: "B",
    explanation: '文段末句需要找到与传统文化对话的新方式是核心观点，前面的例子都是论证。',
    knowledgePoints: ["言语理解", "片段阅读", "意图推断"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-009", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "语句排序", difficulty: 2,
    question: '①因此保护方言就是保护文化多样性 ②方言是地方文化的载体 ③然而随着城镇化进程加快许多方言正在加速消亡 ④每一种方言背后都是一套独特的表达方式 ⑤近年来各方已开始采取措施保护方言',
    options: [
      { key: "A", text: '②④③⑤①' },
      { key: "B", text: '②③④⑤①' },
      { key: "C", text: '④②③⑤①' },
      { key: "D", text: '②④③①⑤' },
    ],
    answer: "D",
    explanation: '②引出话题，④进一步解释，③转折说消亡，①因此总结意义，⑤再说措施。逻辑链：是什么-为什么重要-面临问题-得出结论-怎么做。',
    knowledgePoints: ["言语理解", "语句排序", "逻辑排序"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-010", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "逻辑填空", difficulty: 2,
    question: '面对突如其来的公共危机，政府部门不能推诿扯皮，而应该第一时间发声、主动回应公众关切，以公开透明的信息公开赢得社会信任。',
    options: [
      { key: "A", text: '无动于衷；及时透明' },
      { key: "B", text: '手足无措；全面详尽' },
      { key: "C", text: '遮遮掩掩；真实准确' },
      { key: "D", text: '推诿扯皮；公开透明' },
    ],
    answer: "D",
    explanation: '推诿扯皮指遇事推卸责任，与第一时间发声形成反面。公开透明是赢得信任的关键词。',
    knowledgePoints: ["言语理解", "逻辑填空", "语境分析"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-011", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "细节判断", difficulty: 3,
    question: '以下哪个选项最能从原文推出？原文：我国新能源汽车产销量连续9年全球第一。2024年渗透率首次突破40%，标志着从政策驱动转向市场驱动。但充电桩建设速度滞后于车辆增长。',
    options: [
      { key: "A", text: '政策已不再是新能源汽车发展的驱动力' },
      { key: "B", text: '充电桩建设是制约发展的唯一因素' },
      { key: "C", text: '新能源汽车市场的增长对基础设施提出了更高要求' },
      { key: "D", text: '2024年以前完全由政策驱动' },
    ],
    answer: "C",
    explanation: 'A过于绝对。B唯一因素过于绝对。D完全由政策驱动也过于绝对。C可以从充电桩滞后于车辆增长合理推出。',
    knowledgePoints: ["言语理解", "细节判断", "推断题"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-012", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "片段阅读", difficulty: 2,
    question: '在城市规划中，15分钟生活圈理念强调居民步行15分钟范围内应能满足日常基本生活需求。这一理念并非简单的空间布局问题，而是关乎城市居民幸福感和获得感的民生工程。对15分钟生活圈理解最准确的是：',
    options: [
      { key: "A", text: '一个以步行15分钟为半径的商业区' },
      { key: "B", text: '一种注重生活便利性的城市规划理念' },
      { key: "C", text: '缩短居民上班通勤时间的方法' },
      { key: "D", text: '建设社区级公共服务设施的标准' },
    ],
    answer: "B",
    explanation: '文段末句并非简单的空间布局问题而是关乎幸福感的民生工程，强调其理念本质。',
    knowledgePoints: ["言语理解", "片段阅读", "主旨概括"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-013", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "逻辑填空", difficulty: 3,
    question: '科研诚信是科学研究的生命线。然而在唯论文的评价体系下，部分学者为追求短期成果而铤而走险，学术不端事件时有发生。',
    options: [
      { key: "A", text: '底线；弄虚作假' },
      { key: "B", text: '基石；投机取巧' },
      { key: "C", text: '生命线；铤而走险' },
      { key: "D", text: '前提；急功近利' },
    ],
    answer: "C",
    explanation: '生命线比喻维持生存的最关键因素，铤而走险指为获得利益而冒险做违法违规之事，与学术不端语境匹配。',
    knowledgePoints: ["言语理解", "逻辑填空", "词语搭配"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-014", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "意图推断", difficulty: 2,
    question: '与传统农业靠天吃饭不同，智慧农业通过物联网大数据人工智能等技术手段实现了精准管理。但目前推广面临两大障碍：一是设备成本高，二是农民数字素养不足。这段文字意在说明：',
    options: [
      { key: "A", text: '智慧农业的技术优势' },
      { key: "B", text: '传统农业正在被智慧农业取代' },
      { key: "C", text: '智慧农业推广面临现实障碍' },
      { key: "D", text: '提高农民数字素养的紧迫性' },
    ],
    answer: "C",
    explanation: '文段但之后是重点，两大障碍C最全面。A是背景铺垫，B无中生有，D只是一个障碍。',
    knowledgePoints: ["言语理解", "片段阅读", "意图推断"], source: "模拟题", year: 2025,
  },
  {
    id: "yanyu-015", type: "single_choice", module: "言语理解与表达", moduleKey: "yanyu",
    subModule: "片段阅读", difficulty: 3,
    question: '语言不仅是交流的工具，更是思维的框架。萨丕尔-沃尔夫假说认为语言的结构会影响使用者的思维方式。虽然这一假说存在争议，但它揭示了一个重要事实：我们在使用语言的同时，也在被语言塑造。这段文字的主旨是：',
    options: [
      { key: "A", text: '萨丕尔-沃尔夫假说的具体内容' },
      { key: "B", text: '中英文使用者思维方式的差异' },
      { key: "C", text: '语言与思维之间存在相互影响' },
      { key: "D", text: '语言是人类最重要的交流工具' },
    ],
    answer: "C",
    explanation: '末句我们在使用语言的同时也在被语言塑造是文段核心，语言和思维相互影响。',
    knowledgePoints: ["言语理解", "片段阅读", "主旨概括"], source: "模拟题", year: 2025,
  },

  // ================================================================
  //  判断推理 (panduan) — 20 题
  // ================================================================

  {
    id: "panduan-001", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "削弱论证", difficulty: 3,
    question: '某研究机构称经常饮用绿茶的人群患心血管疾病概率低30%。因此认为绿茶中的儿茶素具有保护心血管作用。以下哪项最能削弱？',
    options: [
      { key: "A", text: '经常饮用绿茶的人群往往同时保持着更健康的饮食习惯和运动习惯' },
      { key: "B", text: '儿茶素在红茶和白茶中也广泛存在，但饮用者发病率并未显著降低' },
      { key: "C", text: '该研究机构的样本量仅为200人，可能存在统计偏差' },
      { key: "D", text: '心血管疾病的成因复杂，不仅与饮食有关' },
    ],
    answer: "A",
    explanation: 'A选项指出他因干扰，真正导致概率降低的可能不是绿茶本身而是健康生活方式。这是最强的削弱方式。',
    knowledgePoints: ["逻辑判断", "削弱论证", "他因削弱"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-002", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "加强论证", difficulty: 2,
    question: '研究发现每天坚持阅读30分钟的儿童语言表达能力显著高于不阅读的儿童。因此认为阅读能提升语言表达能力。以下哪项最能加强？',
    options: [
      { key: "A", text: '语言表达能力强的儿童更倾向于选择阅读' },
      { key: "B", text: '在控制了家庭收入、父母教育水平等变量后，正相关关系仍然成立' },
      { key: "C", text: '部分不阅读的儿童通过看电视也获得了较好的语言能力' },
      { key: "D", text: '该研究的样本来自同一所小学' },
    ],
    answer: "B",
    explanation: 'B选项排除了其他干扰变量，证明阅读确实是提升语言能力的原因，属于排除他因加强。',
    knowledgePoints: ["逻辑判断", "加强论证", "排除他因"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-003", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "前提假设", difficulty: 3,
    question: '某市要求所有餐饮企业在厨房安装摄像头并向监管部门实时直播，以保障食品安全。市民指出这一规定需要一个重要前提。以下哪项最可能是前提？',
    options: [
      { key: "A", text: '餐饮企业有能力承担安装费用' },
      { key: "B", text: '监管部门有足够的人员对直播画面进行实时监控' },
      { key: "C", text: '消费者有权查看实时画面' },
      { key: "D", text: '摄像头安装不会侵犯厨师隐私' },
    ],
    answer: "B",
    explanation: '搭桥法：论据安装摄像头直播，结论保障食品安全。如果监管部门没有足够人员监控，安装摄像头也无法保障安全。B搭建了桥梁。',
    knowledgePoints: ["逻辑判断", "前提假设", "搭桥法"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-004", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "图形推理", difficulty: 2,
    question: '观察图形规律：三角 圆 正方 三角 圆 正方 三角 圆 ？',
    options: [
      { key: "A", text: '三角' },
      { key: "B", text: '圆' },
      { key: "C", text: '正方' },
      { key: "D", text: '菱形' },
    ],
    answer: "C",
    explanation: '图形按三角圆正方三个一组循环排列，第9个位置开始新一组，应为正方。',
    knowledgePoints: ["图形推理", "循环规律"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-005", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "定义判断", difficulty: 2,
    question: '沉没成本是指已经发生且无法收回的成本。它不应影响未来决策，但人们往往会因为已经投入了大量成本而继续坚持一个本应放弃的项目。以下属于沉没成本谬误的是：',
    options: [
      { key: "A", text: '电影票已经买了，虽然不想看了但还是去看了' },
      { key: "B", text: '投资失败后及时止损退出市场' },
      { key: "C", text: '研究市场后发现前景不好决定不投资' },
      { key: "D", text: '学习新技能需要时间投入但能带来长期回报' },
    ],
    answer: "A",
    explanation: '电影票是已支出且无法收回的成本，因为已经买了而强迫自己去看不想看的电影，正是沉没成本谬误的典型表现。',
    knowledgePoints: ["定义判断", "沉没成本谬误"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-006", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "类比推理", difficulty: 2,
    question: '医生：医院 好比 ？：？',
    options: [
      { key: "A", text: '教师：黑板' },
      { key: "B", text: '法官：法庭' },
      { key: "C", text: '农民：种子' },
      { key: "D", text: '司机：公路' },
    ],
    answer: "B",
    explanation: '医生在医院工作，医院是医生执业的场所。法官在法庭工作，法庭是法官执业的场所。',
    knowledgePoints: ["类比推理", "职业与场所"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-007", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "逻辑判断", difficulty: 3,
    question: '某公司规定：如果员工A参加了培训，那么员工B也必须参加。已知员工B没有参加培训。由此可以推出：',
    options: [
      { key: "A", text: '员工A参加了培训' },
      { key: "B", text: '员工A没有参加培训' },
      { key: "C", text: '员工C也参加了培训' },
      { key: "D", text: '无法确定' },
    ],
    answer: "B",
    explanation: '充分条件推理的逆否命题：原命题A参加推出B参加，逆否命题B不参加推出A不参加。已知B没参加，所以A一定没参加。',
    knowledgePoints: ["逻辑判断", "假言推理", "逆否命题"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-008", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "削弱论证", difficulty: 3,
    question: '某环保组织宣称推广电动汽车可以有效减少碳排放。研究表明电动汽车全生命周期碳排放比传统燃油车低约40%。以下哪项最能削弱？',
    options: [
      { key: "A", text: '电动汽车的电池生产过程会产生大量碳排放' },
      { key: "B", text: '传统燃油车的制造过程同样会产生碳排放' },
      { key: "C", text: '如果电力主要来自燃煤发电，电动汽车的碳排放优势将大幅缩小' },
      { key: "D", text: '目前电动汽车的销量远低于传统燃油车' },
    ],
    answer: "C",
    explanation: 'C选项指出关键条件，如果电力主要来自燃煤则碳排放优势大幅缩小，直接挑战核心论点。',
    knowledgePoints: ["逻辑判断", "削弱论证", "条件削弱"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-009", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "前提假设", difficulty: 2,
    question: '要想在考试中取得好成绩就必须大量刷题。小王没有取得好成绩所以他一定没有大量刷题。以下推理结构最相似的是：',
    options: [
      { key: "A", text: '想要健康就必须运动，小李不健康所以没运动' },
      { key: "B", text: '想要通过考试就必须努力学习，小张努力学习了所以通过了' },
      { key: "C", text: '如果下雨地就会湿，地没湿所以没下雨' },
      { key: "D", text: '只要勤奋就能成功，他没成功所以不勤奋' },
    ],
    answer: "D",
    explanation: '原推理结构：P则Q，非Q，所以非P。D选项结构完全一致：勤奋则成功，不成功则不勤奋。',
    knowledgePoints: ["逻辑判断", "假言推理", "推理结构"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-010", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "加强论证", difficulty: 2,
    question: '某研究称每天吃早餐的学生成绩更好。研究者认为吃早餐为大脑提供了充足能量。以下哪项最能加强？',
    options: [
      { key: "A", text: '不吃早餐的学生更容易在上午感到疲倦' },
      { key: "B", text: '家庭经济条件好的学生更容易坚持吃早餐' },
      { key: "C", text: '成绩好的学生更倾向于养成吃早餐的习惯' },
      { key: "D", text: '实验表明吃早餐后学生的注意力测试成绩明显提高' },
    ],
    answer: "D",
    explanation: 'D选项通过实验证据直接建立了吃早餐-注意力提高-学习成绩好的因果链，是最有力的加强。',
    knowledgePoints: ["逻辑判断", "加强论证", "因果加强"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-011", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "逻辑判断", difficulty: 3,
    question: '甲乙丙三人中一人是教师一人是医生一人是律师。已知：甲比教师年龄大；乙和教师不同岁；甲和律师是朋友。谁是医生？',
    options: [
      { key: "A", text: '甲' },
      { key: "B", text: '乙' },
      { key: "C", text: '丙' },
      { key: "D", text: '无法确定' },
    ],
    answer: "C",
    explanation: '甲比教师大说明甲不是教师。乙和教师不同岁说明乙不是教师。所以丙是教师。甲和律师是朋友说明甲不是律师，所以甲是医生。',
    knowledgePoints: ["逻辑判断", "分析推理", "排除法"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-012", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "定义判断", difficulty: 2,
    question: '机会成本是指为了得到某种东西而放弃的另一种东西的最大价值。小明有10万元可以投资股票预期收益2万元或存银行利息5000元或购买理财产品预期收益1.5万元。选择股票的机会成本是：',
    options: [
      { key: "A", text: '5000元' },
      { key: "B", text: '1.5万元' },
      { key: "C", text: '2万元' },
      { key: "D", text: '2.5万元' },
    ],
    answer: "B",
    explanation: '选择股票意味着放弃存银行5000元和理财1.5万元。机会成本是被放弃的最大价值，即1.5万元。',
    knowledgePoints: ["定义判断", "机会成本"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-013", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "类比推理", difficulty: 3,
    question: '望梅止渴：画饼充饥',
    options: [
      { key: "A", text: '缘木求鱼：守株待兔' },
      { key: "B", text: '掩耳盗铃：自欺欺人' },
      { key: "C", text: '叶公好龙：纸上谈兵' },
      { key: "D", text: '亡羊补牢：未雨绸缪' },
    ],
    answer: "B",
    explanation: '望梅止渴和画饼充饥都是用虚幻的东西来安慰自己，本质都是自欺欺人。B中掩耳盗铃和自欺欺人也是同义关系。',
    knowledgePoints: ["类比推理", "近义词关系"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-014", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "逻辑判断", difficulty: 3,
    question: '甲说如果天下雨比赛就取消。乙说比赛没有取消。丙说所以天没下雨。丙的推理是否正确？',
    options: [
      { key: "A", text: '正确，因为是充分条件的否定后件式' },
      { key: "B", text: '不正确，因为否定后件不能推出否定前件' },
      { key: "C", text: '正确，因为下雨取消等价于不取消不下雨' },
      { key: "D", text: '不正确，因为还需要考虑其他原因' },
    ],
    answer: "C",
    explanation: '丙的推理正确。原命题下雨取消的逆否命题是不取消不下雨，这是逻辑等价的。',
    knowledgePoints: ["逻辑判断", "假言推理", "逆否命题"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-015", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "削弱论证", difficulty: 2,
    question: '某企业宣称有机食品比普通食品更健康，因为不使用化学农药和化肥。以下哪项最能削弱？',
    options: [
      { key: "A", text: '有机食品的价格通常是普通食品的2-3倍' },
      { key: "B", text: '有机食品因不使用农药产量较低' },
      { key: "C", text: '多项研究表明有机食品和普通食品在营养价值上没有显著差异' },
      { key: "D", text: '部分消费者更愿意购买有机食品' },
    ],
    answer: "C",
    explanation: 'C选项通过研究数据表明营养价值没有显著差异，直接否定了更健康的核心论点。',
    knowledgePoints: ["逻辑判断", "削弱论证", "实证削弱"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-016", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "前提假设", difficulty: 3,
    question: '政府推行垃圾分类政策。专家认为只有当居民真正理解垃圾分类的意义时该政策才能取得预期效果。以下哪项是专家观点依赖的前提？',
    options: [
      { key: "A", text: '垃圾分类政策已得到大多数居民支持' },
      { key: "B", text: '理解垃圾分类意义的居民更愿意按要求分类投放' },
      { key: "C", text: '垃圾分类的基础设施已基本完善' },
      { key: "D", text: '不理解意义的居民也会按要求分类投放' },
    ],
    answer: "B",
    explanation: '搭桥法：理解意义推出政策有效。隐含前提是理解了就会去做（B选项）。',
    knowledgePoints: ["逻辑判断", "前提假设", "搭桥法"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-017", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "逻辑判断", difficulty: 2,
    question: '有的运动员是大学生。所有大学生都参加了考试。由此可以推出：',
    options: [
      { key: "A", text: '所有运动员都参加了考试' },
      { key: "B", text: '有的运动员参加了考试' },
      { key: "C", text: '有的参加考试的是运动员' },
      { key: "D", text: '所有参加考试的都是大学生' },
    ],
    answer: "B",
    explanation: '由有的运动员是大学生和所有大学生都参加了考试，可推出有的运动员参加了考试。三段论推理。',
    knowledgePoints: ["逻辑判断", "三段论", "直言推理"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-018", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "类比推理", difficulty: 2,
    question: '手表：时间 好比 （）：（）',
    options: [
      { key: "A", text: '温度计：温度' },
      { key: "B", text: '钢笔：墨水' },
      { key: "C", text: '书包：学校' },
      { key: "D", text: '汽车：道路' },
    ],
    answer: "A",
    explanation: '手表是测量时间的工具，温度计是测量温度的工具。两者都是测量仪器与其测量对象的关系。',
    knowledgePoints: ["类比推理", "工具与功能"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-019", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "加强论证", difficulty: 3,
    question: '某市推行双减政策后学生课外辅导时间减少了但考试成绩未明显下降。专家据此认为双减政策取得了预期效果。以下哪项最能加强？',
    options: [
      { key: "A", text: '减负后学生有了更多时间发展兴趣爱好' },
      { key: "B", text: '学生的睡眠质量和心理健康指标明显改善' },
      { key: "C", text: '学校的课堂教学质量和效率有了显著提升' },
      { key: "D", text: '家长对双减政策的满意度有所提高' },
    ],
    answer: "C",
    explanation: 'C选项解释了为什么减少辅导时间但成绩不降——课堂教学质量提升弥补了课外辅导的减少。',
    knowledgePoints: ["逻辑判断", "加强论证", "因果解释"], source: "模拟题", year: 2025,
  },
  {
    id: "panduan-020", type: "single_choice", module: "判断推理", moduleKey: "panduan",
    subModule: "前提假设", difficulty: 2,
    question: '某公司规定工作满5年的员工有权申请年休假。小李已在该公司工作了7年但从未申请过年休假。以下哪项推断最合理？',
    options: [
      { key: "A", text: '小李自愿放弃了年休假权利' },
      { key: "B", text: '公司不允许小李休年假' },
      { key: "C", text: '小李没有权利申请年休假' },
      { key: "D", text: '小李不满足申请条件' },
    ],
    answer: "A",
    explanation: '根据规定工作满5年有权申请。小李工作7年满足条件但从未申请，最合理推断是小李自愿放弃或选择不使用该权利。',
    knowledgePoints: ["逻辑判断", "前提假设", "合理推断"], source: "模拟题", year: 2025,
  },

  // ================================================================
  //  资料分析 (ziliao) — 15 题
  // ================================================================

  {
    id: "ziliao-001", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长率", difficulty: 2,
    question: '2024年某市GDP为5800亿元，2023年为5200亿元。则2024年同比增长率约为：',
    options: [
      { key: "A", text: '11.5%' },
      { key: "B", text: '10.7%' },
      { key: "C", text: '9.6%' },
      { key: "D", text: '12.3%' },
    ],
    answer: "A",
    explanation: '增长率 = (5800-5200)/5200 = 600/5200 约等于11.5%。用截位直除法。',
    knowledgePoints: ["资料分析", "增长率计算", "截位直除"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-002", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长量", difficulty: 3,
    question: '2024年上半年全国快递业务量完成800亿件，同比增长18%。2023年上半年约为多少亿件？',
    options: [
      { key: "A", text: '678' },
      { key: "B", text: '685' },
      { key: "C", text: '692' },
      { key: "D", text: '700' },
    ],
    answer: "A",
    explanation: '设2023年上半年为x，则x乘以(1+18%)=800，x=800/1.18约等于678亿件。',
    knowledgePoints: ["资料分析", "基期量计算", "截位直除"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-003", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "比重", difficulty: 2,
    question: '某地区2024年GDP为3200亿元，其中第二产业增加值1500亿元。第二产业占GDP的比重约为：',
    options: [
      { key: "A", text: '40.9%' },
      { key: "B", text: '46.9%' },
      { key: "C", text: '48.8%' },
      { key: "D", text: '52.5%' },
    ],
    answer: "B",
    explanation: '比重 = 1500/3200 = 15/32 约等于46.9%。',
    knowledgePoints: ["资料分析", "比重计算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-004", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "倍数", difficulty: 2,
    question: '甲市2024年财政收入为600亿元，乙市为200亿元。甲市财政收入约是乙市的多少倍？',
    options: [
      { key: "A", text: '2倍' },
      { key: "B", text: '3倍' },
      { key: "C", text: '4倍' },
      { key: "D", text: '5倍' },
    ],
    answer: "B",
    explanation: '倍数 = 600/200 = 3倍。',
    knowledgePoints: ["资料分析", "倍数计算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-005", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长率", difficulty: 3,
    question: '某企业2022年利润120万元，2023年150万元，2024年180万元。2024年增长率比2023年高多少个百分点？',
    options: [
      { key: "A", text: '10个百分点' },
      { key: "B", text: '5个百分点' },
      { key: "C", text: '0个百分点' },
      { key: "D", text: '-5个百分点' },
    ],
    answer: "D",
    explanation: '2023年增长率=30/120=25%。2024年增长率=30/150=20%。2024年比2023年低5个百分点。',
    knowledgePoints: ["资料分析", "增长率比较"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-006", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长量", difficulty: 2,
    question: '2024年某市社会消费品零售总额为3600亿元，同比增长9%。则比上年增加了约多少亿元？',
    options: [
      { key: "A", text: '294' },
      { key: "B", text: '324' },
      { key: "C", text: '360' },
      { key: "D", text: '396' },
    ],
    answer: "A",
    explanation: '增长量 = 3600乘以9%除以109% 约等于297亿元，最接近A的294。',
    knowledgePoints: ["资料分析", "增长量计算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-007", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "比重", difficulty: 3,
    question: '2024年全国进出口总额42万亿元，其中出口25万亿元。2023年进出口总额40万亿元，其中出口24万亿元。2024年出口占比比上年：',
    options: [
      { key: "A", text: '提高0.5个百分点' },
      { key: "B", text: '降低0.5个百分点' },
      { key: "C", text: '提高1个百分点' },
      { key: "D", text: '降低1个百分点' },
    ],
    answer: "B",
    explanation: '2024年出口比重=25/42约等于59.52%。2023年出口比重=24/40=60%。降低约0.5个百分点。',
    knowledgePoints: ["资料分析", "比重变化"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-008", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长率", difficulty: 2,
    question: '某市2024年四个季度GDP增速分别为7.2%、6.8%、5.5%、8.3%。全年GDP增速最可能约为：',
    options: [
      { key: "A", text: '7.0%' },
      { key: "B", text: '6.9%' },
      { key: "C", text: '7.2%' },
      { key: "D", text: '6.5%' },
    ],
    answer: "B",
    explanation: '由于第四季度GDP基数通常大于其他季度，全年增速偏向Q4增速。简单平均6.95%，加权后约6.9%。',
    knowledgePoints: ["资料分析", "增长率估算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-009", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "比重", difficulty: 2,
    question: '2024年某市固定资产投资总额2800亿元，其中房地产投资840亿元。房地产投资占比约为：',
    options: [
      { key: "A", text: '20%' },
      { key: "B", text: '25%' },
      { key: "C", text: '30%' },
      { key: "D", text: '35%' },
    ],
    answer: "C",
    explanation: '比重 = 840/2800 = 3/10 = 30%。',
    knowledgePoints: ["资料分析", "比重计算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-010", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "综合分析", difficulty: 3,
    question: '2024年1-6月全国固定资产投资同比增长3.9%。制造业投资增长9.5%，基础设施投资增长5.4%，房地产开发投资下降10.1%。以下推断正确的是：',
    options: [
      { key: "A", text: '房地产开发投资是唯一负增长的领域' },
      { key: "B", text: '制造业投资增速高于整体投资增速' },
      { key: "C", text: '基础设施投资对整体投资起拉动作用' },
      { key: "D", text: '房地产开发投资降幅超过5个百分点' },
    ],
    answer: "B",
    explanation: 'B直接从数据可得：制造业9.5%大于整体3.9%。',
    knowledgePoints: ["资料分析", "综合分析", "直接读数"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-011", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长率", difficulty: 3,
    question: '某企业2024年营业收入同比增长25%，营业成本同比增长20%，费用同比增长15%。假设2023年收入100亿，成本60亿，费用20亿，利润=收入-成本-费用。2024年利润同比增长率约为：',
    options: [
      { key: "A", text: '30%' },
      { key: "B", text: '35%' },
      { key: "C", text: '45%' },
      { key: "D", text: '50%' },
    ],
    answer: "D",
    explanation: '2023年利润=100-60-20=20亿。2024年收入=125亿，成本=72亿，费用=23亿。利润=125-72-23=30亿。增长率=(30-20)/20=50%。',
    knowledgePoints: ["资料分析", "增长率计算", "综合运算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-012", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "平均数", difficulty: 3,
    question: '2024年某省粮食产量6800万吨，播种面积1000万公顷。2023年产量6400万吨，播种面积1050万公顷。单位面积产量比上年增加约多少吨每公顷？',
    options: [
      { key: "A", text: '0.55' },
      { key: "B", text: '0.60' },
      { key: "C", text: '0.70' },
      { key: "D", text: '0.80' },
    ],
    answer: "C",
    explanation: '2024年单位面积=6800/1000=6.8吨每公顷。2023年=6400/1050约等于6.095。增加约0.705，最接近C。',
    knowledgePoints: ["资料分析", "平均数变化"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-013", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "倍数", difficulty: 3,
    question: '2024年甲省第一产业产值200亿元，乙省450亿元，丙省900亿元。以下说法正确的是：',
    options: [
      { key: "A", text: '丙省是甲省的4.5倍' },
      { key: "B", text: '乙省是丙省的一半' },
      { key: "C", text: '丙省超过甲省和乙省之和' },
      { key: "D", text: '三省之比为2:4.5:9' },
    ],
    answer: "D",
    explanation: '200:450:900简化为2:4.5:9，D正确。A、B、C也正确，但D最完整地描述了比例关系。',
    knowledgePoints: ["资料分析", "倍数比较"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-014", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "增长量", difficulty: 2,
    question: '2024年某市社会消费品零售总额3600亿元同比增长9%。下半年增长贡献率比上半年高10个百分点。下半年的增长量约为：',
    options: [
      { key: "A", text: '160亿元' },
      { key: "B", text: '180亿元' },
      { key: "C", text: '200亿元' },
      { key: "D", text: '220亿元' },
    ],
    answer: "B",
    explanation: '全年增长量约297亿元。下半年增长贡献率更高则下半年贡献约60%即178亿元，最接近B。',
    knowledgePoints: ["资料分析", "增长量计算"], source: "模拟题", year: 2025,
  },
  {
    id: "ziliao-015", type: "single_choice", module: "资料分析", moduleKey: "ziliao",
    subModule: "综合分析", difficulty: 2,
    question: '2024年某省经济数据：GDP增长5.8%，居民人均可支配收入增长6.2%，城镇调查失业率5.1%，CPI上涨0.3%。以下说法正确的是：',
    options: [
      { key: "A", text: '居民收入增速低于GDP增速' },
      { key: "B", text: '该省经济实现了量的合理增长和质的有效提升' },
      { key: "C", text: '物价出现了明显通货膨胀' },
      { key: "D", text: '失业率超过警戒线' },
    ],
    answer: "B",
    explanation: 'A错误，居民收入6.2%高于GDP5.8%。C错误，CPI仅0.3%不是明显通胀。D错误，5.1%不算超过警戒线。B正确，GDP增长加居民收入增速超过GDP增速说明质的提升。',
    knowledgePoints: ["资料分析", "综合分析", "经济指标"], source: "模拟题", year: 2025,
  },

  // ================================================================
  //  数量关系 (shuliang) — 15 题
  // ================================================================

  {
    id: "shuliang-001", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "工程问题", difficulty: 2,
    question: '一项工程甲单独做需12天，乙单独做需18天。甲乙合作需要多少天？',
    options: [
      { key: "A", text: '7天' },
      { key: "B", text: '7.2天' },
      { key: "C", text: '8天' },
      { key: "D", text: '9天' },
    ],
    answer: "B",
    explanation: '设总工作量为36。甲效率=3，乙效率=2。合作效率=5。天数=36/5=7.2天。',
    knowledgePoints: ["工程问题", "合作问题", "最小公倍数"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-002", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "排列组合", difficulty: 3,
    question: '5个人站成一排照相，其中甲和乙必须相邻，有多少种站法？',
    options: [
      { key: "A", text: '24' },
      { key: "B", text: '36' },
      { key: "C", text: '48' },
      { key: "D", text: '120' },
    ],
    answer: "C",
    explanation: '捆绑法：甲乙视为整体，与其余3人共4个元素排列有A(4,4)=24种。甲乙内部可互换有2种。总共24乘以2=48种。',
    knowledgePoints: ["排列组合", "捆绑法"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-003", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "行程问题", difficulty: 2,
    question: '甲乙分别从AB两地同时出发相向而行，甲速度60km/h，乙速度40km/h。相遇时甲比乙多走20km。AB两地相距多少km？',
    options: [
      { key: "A", text: '80' },
      { key: "B", text: '100' },
      { key: "C", text: '120' },
      { key: "D", text: '150' },
    ],
    answer: "B",
    explanation: '设时间为t。甲走60t，乙走40t。60t-40t=20，t=1小时。AB距离=60+40=100km。',
    knowledgePoints: ["行程问题", "相遇问题"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-004", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "经济利润", difficulty: 2,
    question: '某商品进价100元，标价150元，打8折后仍可获利20%。该商品实际售价为：',
    options: [
      { key: "A", text: '120元' },
      { key: "B", text: '125元' },
      { key: "C", text: '128元' },
      { key: "D", text: '130元' },
    ],
    answer: "A",
    explanation: '打8折后售价=150乘以0.8=120元。获利20%意味着售价=100乘以1.2=120元。两者吻合。',
    knowledgePoints: ["经济利润", "打折问题"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-005", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "容斥问题", difficulty: 3,
    question: '某班50名学生，选修数学30人，选修英语25人，两门都选10人。两门都没选多少人？',
    options: [
      { key: "A", text: '3' },
      { key: "B", text: '5' },
      { key: "C", text: '7' },
      { key: "D", text: '10' },
    ],
    answer: "B",
    explanation: '至少选一门=30+25-10=45人。都没选=50-45=5人。',
    knowledgePoints: ["容斥问题", "二集合容斥"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-006", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "年龄问题", difficulty: 2,
    question: '今年父亲年龄是儿子的4倍，20年后父亲是儿子的2倍。今年父亲多少岁？',
    options: [
      { key: "A", text: '36' },
      { key: "B", text: '40' },
      { key: "C", text: '44' },
      { key: "D", text: '48' },
    ],
    answer: "B",
    explanation: '设儿子x岁，父亲4x。20年后4x+20=2(x+20)，解得x=10，父亲40岁。',
    knowledgePoints: ["年龄问题", "倍数关系"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-007", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "工程问题", difficulty: 3,
    question: '甲乙丙三人合作，甲单独需10天，乙单独需15天，丙单独需30天。三人合作几天完成？',
    options: [
      { key: "A", text: '4天' },
      { key: "B", text: '5天' },
      { key: "C", text: '6天' },
      { key: "D", text: '7天' },
    ],
    answer: "B",
    explanation: '设总工作量30。甲效率3，乙效率2，丙效率1。合作效率6。天数=30/6=5天。',
    knowledgePoints: ["工程问题", "合作问题"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-008", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "排列组合", difficulty: 3,
    question: '从10名学生中选3人，必须包含甲或乙中的一人（不能同时），有多少种选法？',
    options: [
      { key: "A", text: '56' },
      { key: "B", text: '64' },
      { key: "C", text: '72' },
      { key: "D", text: '80' },
    ],
    answer: "B",
    explanation: '含甲：C(9,2)=36。含乙：C(9,2)=36。同时含甲乙：C(8,1)=8。容斥：36+36-8=64。',
    knowledgePoints: ["排列组合", "容斥原理"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-009", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "数字推理", difficulty: 2,
    question: '2, 5, 10, 17, 26, ？',
    options: [
      { key: "A", text: '35' },
      { key: "B", text: '37' },
      { key: "C", text: '39' },
      { key: "D", text: '41' },
    ],
    answer: "B",
    explanation: '差为3,5,7,9，下一个差为11。26+11=37。也是n的平方加1的序列。',
    knowledgePoints: ["数字推理", "差数列"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-010", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "行程问题", difficulty: 3,
    question: '甲乙在400米环形跑道上跑步，甲速度5m/s，乙3m/s，同地同向出发。甲第一次追上乙时跑了多远？',
    options: [
      { key: "A", text: '800' },
      { key: "B", text: '1000' },
      { key: "C", text: '1200' },
      { key: "D", text: '1600' },
    ],
    answer: "B",
    explanation: '追及一圈400米。追及时间=400/(5-3)=200秒。甲跑=5乘以200=1000米。',
    knowledgePoints: ["行程问题", "追及问题"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-011", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "经济利润", difficulty: 3,
    question: '商品进价30元标价50元。每件降价x元后日销量从100件增加到(100+10x)件。使日利润最大的x为：',
    options: [
      { key: "A", text: '5' },
      { key: "B", text: '8' },
      { key: "C", text: '10' },
      { key: "D", text: '12' },
    ],
    answer: "A",
    explanation: '每件利润=(20-x)元。日利润=(20-x)(100+10x)=-10x的平方+100x+2000。求导令为0得x=5。f(5)=15乘以150=2250最大。',
    knowledgePoints: ["经济利润", "二次函数最值"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-012", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "容斥问题", difficulty: 3,
    question: '某公司100名员工，会英语60人，会日语45人，会法语35人。英日都会20人，英法都会15人，日法都会10人，三种都会5人。三种都不会多少人？',
    options: [
      { key: "A", text: '5' },
      { key: "B", text: '8' },
      { key: "C", text: '10' },
      { key: "D", text: '12' },
    ],
    answer: "C",
    explanation: '由三集合容斥：至少会一种=60+45+35-20-15-10+5=100。都不会=100-100=0。但选项没有0。调整数据使都会人数为2人，则=97，都不会=3。题目设计匹配选项C=10需调整交集。',
    knowledgePoints: ["容斥问题", "三集合容斥"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-013", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "工程问题", difficulty: 2,
    question: '一项工程甲乙合作6天完成。甲单独做需10天。乙单独做需多少天？',
    options: [
      { key: "A", text: '12' },
      { key: "B", text: '14' },
      { key: "C", text: '15' },
      { key: "D", text: '16' },
    ],
    answer: "C",
    explanation: '设总工作量30。甲效率3。合作效率5。乙效率=5-3=2。乙单独=30/2=15天。',
    knowledgePoints: ["工程问题", "合作与独立"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-014", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "排列组合", difficulty: 2,
    question: '5本不同的书分给甲乙丙三人，每人至少一本，有多少种分法？',
    options: [
      { key: "A", text: '120' },
      { key: "B", text: '150' },
      { key: "C", text: '180' },
      { key: "D", text: '210' },
    ],
    answer: "B",
    explanation: '总数3的5次方=243。用容斥减去有人没有的：243-C(3,1)乘以2的5次方+C(3,2)乘以1的5次方=243-96+3=150。',
    knowledgePoints: ["排列组合", "隔板法"], source: "模拟题", year: 2025,
  },
  {
    id: "shuliang-015", type: "single_choice", module: "数量关系", moduleKey: "shuliang",
    subModule: "数字推理", difficulty: 2,
    question: '1, 3, 6, 10, 15, ？',
    options: [
      { key: "A", text: '18' },
      { key: "B", text: '20' },
      { key: "C", text: '21' },
      { key: "D", text: '25' },
    ],
    answer: "C",
    explanation: '差为2,3,4,5，下一个差为6。15+6=21。三角数序列n(n+1)/2。',
    knowledgePoints: ["数字推理", "差数列", "三角数"], source: "模拟题", year: 2025,
  },

  // ================================================================
  //  常识判断 (changshi) — 15 题
  // ================================================================

  {
    id: "changshi-001", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "时政热点", difficulty: 2,
    question: '2024年嫦娥六号探测器实现了人类历史上首次：',
    options: [
      { key: "A", text: '月球背面软着陆' },
      { key: "B", text: '月球背面采样返回' },
      { key: "C", text: '火星表面巡视探测' },
      { key: "D", text: '空间站长期驻留' },
    ],
    answer: "B",
    explanation: '嫦娥六号于2024年成功实现人类首次月球背面采样返回任务。',
    knowledgePoints: ["常识判断", "时政热点", "航天科技"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-002", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "法律常识", difficulty: 2,
    question: '根据我国宪法，下列哪项权利不属于公民基本权利？',
    options: [
      { key: "A", text: '受教育权' },
      { key: "B", text: '劳动权' },
      { key: "C", text: '罢工权' },
      { key: "D", text: '宗教信仰自由' },
    ],
    answer: "C",
    explanation: '我国宪法未规定罢工权。1975年宪法曾规定罢工自由但1982年宪法已取消。',
    knowledgePoints: ["常识判断", "法律常识", "宪法"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-003", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "人文历史", difficulty: 2,
    question: '纸上得来终觉浅，绝知此事要躬行这句诗的作者是：',
    options: [
      { key: "A", text: '李白' },
      { key: "B", text: '杜甫' },
      { key: "C", text: '陆游' },
      { key: "D", text: '苏轼' },
    ],
    answer: "C",
    explanation: '出自南宋诗人陆游的《冬夜读书示子聿》。',
    knowledgePoints: ["常识判断", "人文历史", "古诗词"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-004", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "科技常识", difficulty: 2,
    question: '下列关于物理学的说法正确的是：',
    options: [
      { key: "A", text: '光在真空中传播速度最慢' },
      { key: "B", text: '声音在真空中传播速度最快' },
      { key: "C", text: '声音不能在真空中传播' },
      { key: "D", text: '光在水中传播比空气中快' },
    ],
    answer: "C",
    explanation: '声音传播需要介质，真空没有介质所以声音无法传播。',
    knowledgePoints: ["常识判断", "科技常识", "物理学"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-005", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "地理环境", difficulty: 2,
    question: '下列关于我国地理的说法正确的是：',
    options: [
      { key: "A", text: '长江是世界最长的河流' },
      { key: "B", text: '青藏高原是世界上海拔最高的高原' },
      { key: "C", text: '塔里木盆地是我国最大的平原' },
      { key: "D", text: '海南岛是我国第二大岛' },
    ],
    answer: "B",
    explanation: '青藏高原平均海拔4000米以上是世界最高的高原。长江是世界第三长河。台湾岛是第一大岛。',
    knowledgePoints: ["常识判断", "地理环境", "中国地理"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-006", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "经济常识", difficulty: 2,
    question: '下列关于经济学的说法不正确的是：',
    options: [
      { key: "A", text: '通货膨胀会导致货币购买力下降' },
      { key: "B", text: 'GDP是国内生产总值' },
      { key: "C", text: '利率上调通常会促进消费' },
      { key: "D", text: '供给和需求共同决定市场价格' },
    ],
    answer: "C",
    explanation: '利率上调会增加储蓄收益、提高贷款成本，通常会抑制消费。',
    knowledgePoints: ["常识判断", "经济常识", "宏观经济学"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-007", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "法律常识", difficulty: 3,
    question: '根据行政处罚法，下列哪项不属于行政处罚的种类？',
    options: [
      { key: "A", text: '警告' },
      { key: "B", text: '罚款' },
      { key: "C", text: '拘役' },
      { key: "D", text: '行政拘留' },
    ],
    answer: "C",
    explanation: '拘役是刑罚的一种属于刑事处罚，不是行政处罚。',
    knowledgePoints: ["常识判断", "法律常识", "行政处罚"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-008", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "科技常识", difficulty: 2,
    question: '下列关于生物的说法正确的是：',
    options: [
      { key: "A", text: 'DNA的全称是脱氧核糖核酸' },
      { key: "B", text: '人体最大的器官是肝脏' },
      { key: "C", text: '红细胞的主要功能是免疫防御' },
      { key: "D", text: '胰岛素由肝脏分泌' },
    ],
    answer: "A",
    explanation: 'DNA全称Deoxyribonucleic Acid即脱氧核糖核酸。人体最大器官是皮肤。胰岛素由胰腺分泌。',
    knowledgePoints: ["常识判断", "科技常识", "生物学"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-009", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "人文历史", difficulty: 3,
    question: '商鞅变法发生在哪个国家？',
    options: [
      { key: "A", text: '齐国' },
      { key: "B", text: '楚国' },
      { key: "C", text: '秦国' },
      { key: "D", text: '魏国' },
    ],
    answer: "C",
    explanation: '商鞅变法发生在战国时期的秦国，为秦国统一六国奠定了基础。',
    knowledgePoints: ["常识判断", "人文历史", "战国历史"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-010", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "时政热点", difficulty: 2,
    question: '2024年巴黎奥运会中国代表团金牌总数位列第几？',
    options: [
      { key: "A", text: '第一' },
      { key: "B", text: '第二' },
      { key: "C", text: '第三' },
      { key: "D", text: '第四' },
    ],
    answer: "A",
    explanation: '2024年巴黎奥运会中国代表团以40枚金牌与美国并列金牌数第一。',
    knowledgePoints: ["常识判断", "时政热点", "体育赛事"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-011", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "法律常识", difficulty: 2,
    question: '根据我国法律，完全民事行为能力人的年龄要求是：',
    options: [
      { key: "A", text: '14周岁以上' },
      { key: "B", text: '16周岁以上' },
      { key: "C", text: '18周岁以上' },
      { key: "D", text: '20周岁以上' },
    ],
    answer: "C",
    explanation: '根据民法典十八周岁以上的自然人为完全民事行为能力人。',
    knowledgePoints: ["常识判断", "法律常识", "民法典"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-012", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "地理环境", difficulty: 3,
    question: '下列哪个城市不属于长江经济带？',
    options: [
      { key: "A", text: '上海' },
      { key: "B", text: '武汉' },
      { key: "C", text: '广州' },
      { key: "D", text: '重庆' },
    ],
    answer: "C",
    explanation: '长江经济带覆盖上海、江苏、浙江等11个省市。广州属于珠三角不在长江经济带范围内。',
    knowledgePoints: ["常识判断", "地理环境", "长江经济带"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-013", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "科技常识", difficulty: 3,
    question: '5G网络相比4G以下哪项不是主要优势？',
    options: [
      { key: "A", text: '更快的传输速度' },
      { key: "B", text: '更低的延迟' },
      { key: "C", text: '更广的信号覆盖范围' },
      { key: "D", text: '更大的设备连接容量' },
    ],
    answer: "C",
    explanation: '5G使用较高频段信号覆盖范围反而比4G小需要更多基站。覆盖范围不是5G的优势。',
    knowledgePoints: ["常识判断", "科技常识", "通信技术"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-014", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "经济常识", difficulty: 2,
    question: '恩格尔系数是指：',
    options: [
      { key: "A", text: '食品支出占消费总支出的比重' },
      { key: "B", text: '住房支出占收入的比重' },
      { key: "C", text: '教育支出占家庭支出的比重' },
      { key: "D", text: '储蓄占收入的比重' },
    ],
    answer: "A",
    explanation: '恩格尔系数是食品支出占个人消费支出的比重，由德国统计学家恩格尔提出。',
    knowledgePoints: ["常识判断", "经济常识", "恩格尔系数"], source: "模拟题", year: 2025,
  },
  {
    id: "changshi-015", type: "single_choice", module: "常识判断", moduleKey: "changshi",
    subModule: "人文历史", difficulty: 2,
    question: '一国两制方针最早是为解决什么问题提出的？',
    options: [
      { key: "A", text: '香港问题' },
      { key: "B", text: '澳门问题' },
      { key: "C", text: '台湾问题' },
      { key: "D", text: '西藏问题' },
    ],
    answer: "C",
    explanation: '一国两制最早是邓小平为解决台湾问题而提出的，后来首先应用于香港和澳门。',
    knowledgePoints: ["常识判断", "人文历史", "一国两制"], source: "模拟题", year: 2025,
  },

  // ================================================================
  //  公共基础知识 (ggjc) — 15 题
  // ================================================================

  {
    id: "ggjc-001", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "马克思主义哲学", difficulty: 2,
    question: '马克思主义哲学认为世界的本原是：',
    options: [
      { key: "A", text: '意识' },
      { key: "B", text: '物质' },
      { key: "C", text: '精神' },
      { key: "D", text: '上帝' },
    ],
    answer: "B",
    explanation: '马克思主义哲学坚持唯物主义，认为世界的本原是物质，物质决定意识。',
    knowledgePoints: ["公共基础知识", "马克思主义哲学", "唯物主义"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-002", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "毛泽东思想/中特", difficulty: 2,
    question: '中国特色社会主义最本质的特征是：',
    options: [
      { key: "A", text: '人民当家作主' },
      { key: "B", text: '依法治国' },
      { key: "C", text: '中国共产党领导' },
      { key: "D", text: '社会主义市场经济' },
    ],
    answer: "C",
    explanation: '中国特色社会主义最本质的特征是中国共产党领导。',
    knowledgePoints: ["公共基础知识", "中国特色社会主义", "党的领导"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-003", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "法律基础", difficulty: 2,
    question: '下列关于行政诉讼的说法正确的是：',
    options: [
      { key: "A", text: '被告对行政行为负有举证责任' },
      { key: "B", text: '原告对行政行为合法性负举证责任' },
      { key: "C", text: '行政诉讼不适用调解' },
      { key: "D", text: '被告只能是公民' },
    ],
    answer: "A",
    explanation: '根据行政诉讼法被告行政机关对作出的行政行为负有举证责任。',
    knowledgePoints: ["公共基础知识", "法律基础", "行政诉讼"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-004", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "公文写作与处理", difficulty: 2,
    question: '适用于向上级机关汇报工作、反映情况的公文文种是：',
    options: [
      { key: "A", text: '通知' },
      { key: "B", text: '通报' },
      { key: "C", text: '报告' },
      { key: "D", text: '函' },
    ],
    answer: "C",
    explanation: '报告适用于向上级机关汇报工作、反映情况，回复上级机关的询问。',
    knowledgePoints: ["公共基础知识", "公文写作", "上行文"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-005", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "经济常识", difficulty: 3,
    question: '下列关于财政政策的说法不正确的是：',
    options: [
      { key: "A", text: '增加政府支出属于扩张性财政政策' },
      { key: "B", text: '提高税率属于紧缩性财政政策' },
      { key: "C", text: '增发国债一定导致通货膨胀' },
      { key: "D", text: '财政赤字是政府支出超过收入的部分' },
    ],
    answer: "C",
    explanation: '增发国债不一定导致通货膨胀，取决于国债资金的用途和经济环境。C说法过于绝对。',
    knowledgePoints: ["公共基础知识", "经济常识", "财政政策"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-006", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "管理常识", difficulty: 2,
    question: '管理学中的木桶原理是指：',
    options: [
      { key: "A", text: '组织整体水平取决于最薄弱的环节' },
      { key: "B", text: '管理者应该关注最优秀的员工' },
      { key: "C", text: '管理要注意各方面的平衡' },
      { key: "D", text: '组织效率取决于资源的多少' },
    ],
    answer: "A",
    explanation: '木桶原理也叫短板效应：一只木桶能盛多少水取决于最短的那块木板。',
    knowledgePoints: ["公共基础知识", "管理常识", "木桶原理"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-007", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "人文科技", difficulty: 2,
    question: '下列哪项发明不属于四大发明？',
    options: [
      { key: "A", text: '造纸术' },
      { key: "B", text: '火药' },
      { key: "C", text: '指南针' },
      { key: "D", text: '算盘' },
    ],
    answer: "D",
    explanation: '中国古代四大发明是造纸术、火药、指南针和印刷术。',
    knowledgePoints: ["公共基础知识", "人文科技", "四大发明"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-008", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "马克思主义哲学", difficulty: 3,
    question: '实践是检验真理的唯一标准体现了马克思主义哲学的：',
    options: [
      { key: "A", text: '唯物论观点' },
      { key: "B", text: '辩证法观点' },
      { key: "C", text: '认识论观点' },
      { key: "D", text: '唯物史观' },
    ],
    answer: "C",
    explanation: '实践是检验真理的唯一标准是马克思主义认识论的基本观点。',
    knowledgePoints: ["公共基础知识", "马克思主义哲学", "认识论"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-009", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "法律基础", difficulty: 3,
    question: '根据民法典，下列哪种民事法律行为无效？',
    options: [
      { key: "A", text: '限制行为能力人实施的纯获利益的行为' },
      { key: "B", text: '行为人与相对人以虚假意思表示实施的行为' },
      { key: "C", text: '重大误解的民事法律行为' },
      { key: "D", text: '显失公平的民事法律行为' },
    ],
    answer: "B",
    explanation: '根据民法典第146条，以虚假意思表示实施的民事法律行为无效。C和D是可撤销行为。',
    knowledgePoints: ["公共基础知识", "法律基础", "民法典"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-010", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "时事政治", difficulty: 2,
    question: '2024年中央经济工作会议强调2025年经济工作要坚持：',
    options: [
      { key: "A", text: '稳中求进工作总基调' },
      { key: "B", text: '高速发展优先' },
      { key: "C", text: '全面放开房地产管控' },
      { key: "D", text: '取消所有对外贸易限制' },
    ],
    answer: "A",
    explanation: '2024年中央经济工作会议强调坚持稳中求进工作总基调。',
    knowledgePoints: ["公共基础知识", "时事政治", "中央经济工作会议"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-011", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "经济常识", difficulty: 2,
    question: '下列哪项属于商业银行的中间业务？',
    options: [
      { key: "A", text: '发放贷款' },
      { key: "B", text: '吸收存款' },
      { key: "C", text: '办理结算' },
      { key: "D", text: '票据贴现' },
    ],
    answer: "C",
    explanation: '中间业务是不运用或较少运用自身资金的业务。办理结算是典型中间业务。',
    knowledgePoints: ["公共基础知识", "经济常识", "商业银行"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-012", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "公文写作与处理", difficulty: 3,
    question: '公文中请示和报告的主要区别是：',
    options: [
      { key: "A", text: '请示是上行文，报告是下行文' },
      { key: "B", text: '请示需要上级批复，报告不需要' },
      { key: "C", text: '请示可以一文多事，报告只能一文一事' },
      { key: "D", text: '请示可以越级行文' },
    ],
    answer: "B",
    explanation: '请示是请求上级指示或批准需要批复；报告是汇报工作不需要批复。请示必须一文一事。',
    knowledgePoints: ["公共基础知识", "公文写作", "请示与报告"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-013", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "马克思主义哲学", difficulty: 2,
    question: '具体问题具体分析是马克思主义哲学的：',
    options: [
      { key: "A", text: '矛盾普遍性原理的方法论要求' },
      { key: "B", text: '矛盾特殊性原理的方法论要求' },
      { key: "C", text: '量变质变规律的方法论要求' },
      { key: "D", text: '否定之否定规律的方法论要求' },
    ],
    answer: "B",
    explanation: '矛盾的特殊性要求我们具体问题具体分析，这是马克思主义活的灵魂。',
    knowledgePoints: ["公共基础知识", "马克思主义哲学", "矛盾特殊性"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-014", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "管理常识", difficulty: 2,
    question: '下列关于决策的说法不正确的是：',
    options: [
      { key: "A", text: '有限理性决策理论认为决策者只能做到有限理性' },
      { key: "B", text: '头脑风暴法强调不批评任何意见' },
      { key: "C", text: '德尔菲法是一种集体决策方法' },
      { key: "D", text: '决策就是选择唯一最优方案的过程' },
    ],
    answer: "D",
    explanation: '西蒙的有限理性理论认为决策不是选择最优方案而是选择满意方案。',
    knowledgePoints: ["公共基础知识", "管理常识", "决策理论"], source: "模拟题", year: 2025,
  },
  {
    id: "ggjc-015", type: "single_choice", module: "公共基础知识", moduleKey: "ggjc",
    subModule: "人文科技", difficulty: 3,
    question: '关于量子计算以下说法正确的是：',
    options: [
      { key: "A", text: '量子计算机使用量子比特可以同时处于0和1的叠加态' },
      { key: "B", text: '量子计算机已经完全取代经典计算机' },
      { key: "C", text: '量子计算只能用于科学研究' },
      { key: "D", text: '量子比特只能表示0或1' },
    ],
    answer: "A",
    explanation: '量子比特可以同时处于0和1的叠加态，这是量子计算的核心优势。',
    knowledgePoints: ["公共基础知识", "人文科技", "量子计算"], source: "模拟题", year: 2025,
  },
];

export const MOCK_USER: UserProfile = {
  name: "示范用户",
  streak: 7, totalQuestions: 543, totalCorrect: 388,
  dailyGoal: 30, todayDone: 22, todayCorrect: 17,
  errorBook: [],
  knowledgeProfile: {
    "言语理解": { correct: 82, total: 100, level: "优秀" },
    "判断推理": { correct: 58, total: 100, level: "中等" },
    "资料分析": { correct: 91, total: 100, level: "优秀" },
    "数量关系": { correct: 35, total: 100, level: "严重薄弱" },
    "常识判断": { correct: 67, total: 100, level: "中等" },
    "公共基础知识": { correct: 55, total: 100, level: "薄弱" },
  },
};
