"use client";

import threeColorMemoryCards from "@/data/three_color_memory_cards.json";

export type FormulaItem = {
  id: string;
  group: string;
  title: string;
  formula: string;
  note: string;
  blanks: string[];
};

export type FractionItem = {
  id: string;
  group: string;
  front: string;
  back: string;
  hint: string;
};

export type MemoryCard = {
  id: string;
  category: string;
  subcategory: string;
  front: string;
  back: string;
  tags: string[];
};

export const formulaItems: FormulaItem[] = [
  {
    id: "base-current-minus-growth",
    group: "基期与现期",
    title: "已知现期量和增长量求基期量",
    formula: "基期量 = 现期量 - 增长量",
    note: "增长量是现期相对基期多出来的量，先还原到基期。",
    blanks: ["现期量 - 增长量"],
  },
  {
    id: "base-current-growth-rate",
    group: "基期与现期",
    title: "已知现期量和增长率求基期量",
    formula: "基期量 = 现期量 / (1 + 增长率)",
    note: "遇到下降率时，增长率取负值。",
    blanks: ["现期量 / (1 + 增长率)", "1 + 增长率"],
  },
  {
    id: "interval-growth",
    group: "增长",
    title: "间隔增长率",
    formula: "间隔增长率 = r1 + r2 + r1 x r2",
    note: "连续两期增长合并时使用，近似时可先算 r1+r2 再补乘积项。",
    blanks: ["r1 + r2 + r1 x r2"],
  },
  {
    id: "avg-growth-rate",
    group: "增长",
    title: "年均增长率",
    formula: "(1 + 年均增长率)^n = 现期量 / 基期量",
    note: "n 是相隔年数，不是材料出现的年份数量。",
    blanks: ["现期量 / 基期量", "相隔年数"],
  },
  {
    id: "growth-amount-current",
    group: "增长",
    title: "已知现期量和增长率求增长量",
    formula: "增长量 = 现期量 x 增长率 / (1 + 增长率)",
    note: "增长率约等于 1/n 时，增长量可速算为现期量/(n+1)。",
    blanks: ["现期量 x 增长率 / (1 + 增长率)", "现期量/(n+1)"],
  },
  {
    id: "share-current",
    group: "比重",
    title: "现期比重",
    formula: "比重 = 部分 / 整体",
    note: "看清题干问的是部分占整体，还是整体中某部分的贡献。",
    blanks: ["部分 / 整体"],
  },
  {
    id: "share-base",
    group: "比重",
    title: "基期比重",
    formula: "基期比重 = A / B x (1 + b) / (1 + a)",
    note: "A、a 是现期部分量和增长率；B、b 是现期整体量和增长率。",
    blanks: ["A / B x (1 + b) / (1 + a)", "整体增长率 b"],
  },
  {
    id: "share-diff",
    group: "比重",
    title: "两期比重差",
    formula: "两期比重差 = A / B x (a - b) / (1 + a)",
    note: "先用 a 与 b 判断升降，再估算差值；a>b 时比重上升。",
    blanks: ["A / B x (a - b) / (1 + a)", "a > b"],
  },
  {
    id: "avg-base",
    group: "平均数",
    title: "基期平均数",
    formula: "基期平均数 = A / B x (1 + b) / (1 + a)",
    note: "与基期比重同形，A 是总量，B 是份数。",
    blanks: ["A / B x (1 + b) / (1 + a)"],
  },
  {
    id: "avg-growth",
    group: "平均数",
    title: "平均数增长率",
    formula: "平均数增长率 = (a - b) / (1 + b)",
    note: "a 是总量增长率，b 是份数增长率。",
    blanks: ["(a - b) / (1 + b)"],
  },
  {
    id: "multiple-current",
    group: "倍数",
    title: "现期倍数",
    formula: "现期倍数 = A / B",
    note: "A 比 B 多几倍 = A/B - 1。",
    blanks: ["A / B", "A/B - 1"],
  },
  {
    id: "multiple-base",
    group: "倍数",
    title: "基期倍数",
    formula: "基期倍数 = A / B x (1 + b) / (1 + a)",
    note: "与基期比重、基期平均数同形，先判断分子分母增长率。",
    blanks: ["A / B x (1 + b) / (1 + a)"],
  },
];

export const fractionItems: FractionItem[] = [
  { id: "f-1-2", group: "基础百化分", front: "1/2", back: "50%", hint: "一半" },
  { id: "f-1-3", group: "基础百化分", front: "1/3", back: "33.3%", hint: "三三循环" },
  { id: "f-2-3", group: "基础百化分", front: "2/3", back: "66.7%", hint: "一减 1/3" },
  { id: "f-1-4", group: "基础百化分", front: "1/4", back: "25%", hint: "四分之一" },
  { id: "f-3-4", group: "基础百化分", front: "3/4", back: "75%", hint: "三个 25%" },
  { id: "f-1-5", group: "基础百化分", front: "1/5", back: "20%", hint: "五等分" },
  { id: "f-1-6", group: "基础百化分", front: "1/6", back: "16.7%", hint: "约等于 0.167" },
  { id: "f-1-7", group: "基础百化分", front: "1/7", back: "14.3%", hint: "142857 循环" },
  { id: "f-1-8", group: "基础百化分", front: "1/8", back: "12.5%", hint: "半个 25%" },
  { id: "f-1-9", group: "基础百化分", front: "1/9", back: "11.1%", hint: "一一循环" },
  { id: "f-1-11", group: "母子互换", front: "1/11", back: "9.1%", hint: "约等于 0.091" },
  { id: "f-1-12", group: "母子互换", front: "1/12", back: "8.3%", hint: "1/6 的一半" },
  { id: "sq-11", group: "平方数", front: "11^2", back: "121", hint: "常用估算锚点" },
  { id: "sq-12", group: "平方数", front: "12^2", back: "144", hint: "资料分析常见" },
  { id: "sq-13", group: "平方数", front: "13^2", back: "169", hint: "接近 170" },
  { id: "sq-14", group: "平方数", front: "14^2", back: "196", hint: "接近 200" },
  { id: "sq-15", group: "平方数", front: "15^2", back: "225", hint: "四分之一百的 9 倍" },
  { id: "cu-5", group: "立方数", front: "5^3", back: "125", hint: "1/8 的百分数也常见 12.5%" },
  { id: "cu-6", group: "立方数", front: "6^3", back: "216", hint: "常见数量级判断" },
  { id: "unit-acre", group: "单位换算", front: "1 亩", back: "约 667 平方米", hint: "15 亩 = 1 公顷" },
  { id: "unit-hectare", group: "单位换算", front: "1 公顷", back: "15 亩 = 10000 平方米", hint: "土地面积常考" },
  { id: "unit-ton", group: "单位换算", front: "1 吨", back: "1000 千克 = 2000 斤", hint: "重量换算" },
];

const bundledMemoryCards: MemoryCard[] = [
  {
    id: "data-001",
    category: "资料分析",
    subcategory: "增长",
    front: "现期量、基期量、增长量之间如何互推？",
    back: "现期量 = 基期量 + 增长量；基期量 = 现期量 - 增长量。若给增长率，基期量 = 现期量 / (1 + r)。",
    tags: ["公式", "基期"],
  },
  {
    id: "data-002",
    category: "资料分析",
    subcategory: "增长",
    front: "增长率和增长量的阅读顺序是什么？",
    back: "先看时间、主体、单位，再确认问增长率还是增长量。增长率是相对变化，增长量是绝对变化，不能混用。",
    tags: ["审题"],
  },
  {
    id: "data-003",
    category: "资料分析",
    subcategory: "比重",
    front: "两期比重判断升降看什么？",
    back: "看部分增长率 a 与整体增长率 b。a > b，比重上升；a < b，比重下降；差值用 A/B x (a-b)/(1+a) 估算。",
    tags: ["两期比重"],
  },
  {
    id: "data-004",
    category: "资料分析",
    subcategory: "平均数",
    front: "平均数增长率公式是什么？",
    back: "平均数增长率 = (总量增长率 - 份数增长率) / (1 + 份数增长率)。先判断升降，再代入估算。",
    tags: ["平均数"],
  },
  {
    id: "data-005",
    category: "资料分析",
    subcategory: "速算",
    front: "选项差距较大时资料分析如何提速？",
    back: "先截位直除，保留 2-3 位有效数字；差距大于 10% 时可以大胆估算，差距小再精算。",
    tags: ["速算"],
  },
  {
    id: "judgement-001",
    category: "判断推理",
    subcategory: "加强削弱",
    front: "削弱题优先找什么？",
    back: "先找论点和论据，再找论证缺口。常见削弱方式：否定论据、拆桥、另有他因、因果倒置、样本不代表总体。",
    tags: ["逻辑"],
  },
  {
    id: "judgement-002",
    category: "判断推理",
    subcategory: "加强削弱",
    front: "加强题的强度排序如何理解？",
    back: "建立论据到论点的直接关系最强，其次补充必要条件、排除他因、增加正向例证。只重复论点通常不强。",
    tags: ["逻辑"],
  },
  {
    id: "judgement-003",
    category: "判断推理",
    subcategory: "真假推理",
    front: "真假推理题第一步做什么？",
    back: "找矛盾关系。矛盾必一真一假，能直接锁定真假名额；再用剩余条件代入验证。",
    tags: ["真假"],
  },
  {
    id: "graphic-001",
    category: "图形推理",
    subcategory: "数量规律",
    front: "图推数量规律常看哪些元素？",
    back: "点、线、角、面、素。若图形复杂且差异大，优先数面和交点；若图形规整，优先看对称、封闭区间和笔画。",
    tags: ["图推"],
  },
  {
    id: "graphic-002",
    category: "图形推理",
    subcategory: "位置规律",
    front: "图形位置变化题的观察顺序？",
    back: "先看整体移动、旋转、翻转；再看局部元素的相对位置。九宫格常按行、列分别找规律。",
    tags: ["图推"],
  },
  {
    id: "graphic-003",
    category: "图形推理",
    subcategory: "空间重构",
    front: "六面体折叠题如何快速排除？",
    back: "看相对面、公共边、时针方向。相对面不能相邻；三面相邻时公共顶点的顺逆时针关系不能变。",
    tags: ["空间"],
  },
  {
    id: "logic-001",
    category: "逻辑判断",
    subcategory: "翻译推理",
    front: "充分条件和必要条件如何翻译？",
    back: "如果 A 那么 B：A -> B。只有 A 才 B：B -> A。除非 A 否则 B：非 A -> B。",
    tags: ["翻译"],
  },
  {
    id: "logic-002",
    category: "逻辑判断",
    subcategory: "逆否",
    front: "命题 A -> B 的等价命题是什么？",
    back: "等价于 非B -> 非A。不能推出 B -> A，也不能推出 非A -> 非B。",
    tags: ["翻译"],
  },
  {
    id: "logic-003",
    category: "逻辑判断",
    subcategory: "集合",
    front: "“有的 A 是 B”能推出什么？",
    back: "能推出有的 B 是 A。不能推出有的 A 不是 B，也不能推出所有 A 都是 B。",
    tags: ["集合"],
  },
  {
    id: "verbal-001",
    category: "言语理解与表达",
    subcategory: "主旨概括",
    front: "主旨题重点看哪些句子？",
    back: "看转折后、总结句、首尾句和对策句。材料有问题加对策时，对策通常是主旨核心。",
    tags: ["阅读"],
  },
  {
    id: "verbal-002",
    category: "言语理解与表达",
    subcategory: "细节判断",
    front: "细节题常见陷阱有哪些？",
    back: "偷换概念、扩大缩小范围、无中生有、强加因果、时态错位。逐项回原文定位，不凭印象选。",
    tags: ["阅读"],
  },
  {
    id: "verbal-003",
    category: "言语理解",
    subcategory: "逻辑填空",
    front: "逻辑填空先辨析词还是先看语境？",
    back: "先看语境关系：转折、递进、并列、因果、解释说明；再辨析词义轻重、搭配对象和感情色彩。",
    tags: ["填空"],
  },
  {
    id: "quantity-001",
    category: "数量关系",
    subcategory: "工程问题",
    front: "工程问题的核心三量是什么？",
    back: "工作总量、效率、时间。常设总量为效率或时间的公倍数，合作效率相加。",
    tags: ["数量"],
  },
  {
    id: "quantity-002",
    category: "数量关系",
    subcategory: "排列组合",
    front: "相邻和不相邻问题分别用什么方法？",
    back: "相邻用捆绑法，不相邻用插空法。遇到“至少”常先反面考虑，再用总数减去不符合情况。",
    tags: ["排列组合"],
  },
  {
    id: "quantity-003",
    category: "数量关系",
    subcategory: "利润",
    front: "利润率相关公式有哪些？",
    back: "利润 = 售价 - 成本；利润率 = 利润 / 成本；折扣售价 = 原价 x 折扣。看清利润率基准是成本还是售价。",
    tags: ["经济利润"],
  },
  {
    id: "graphic-pdf-001",
    category: "判断推理",
    subcategory: "图形推理",
    front: "图形推理遇到“元素组成相同”时优先看什么？",
    back: "优先看位置规律：平移、旋转、翻转。多元素先标号区分，再分别观察方向、步数和角度。",
    tags: ["图推", "位置规律"],
  },
  {
    id: "graphic-pdf-002",
    category: "判断推理",
    subcategory: "位置规律",
    front: "黑块在 16 宫格中移动，如何判断是绕圈还是直线走？",
    back: "看内圈黑块数量。内圈数量相同，优先内外圈分开看，考虑回字形绕圈；内圈数量不同，优先考虑直线走。",
    tags: ["图推", "平移"],
  },
  {
    id: "graphic-pdf-003",
    category: "判断推理",
    subcategory: "旋转翻转",
    front: "如何区分旋转 180°、左右翻转、上下翻转？",
    back: "只有左右互换且上下不变，是左右翻转；只有上下互换且左右不变，是上下翻转；上下和左右都互换，是旋转 180°。",
    tags: ["图推", "旋转"],
  },
  {
    id: "graphic-pdf-004",
    category: "判断推理",
    subcategory: "样式规律",
    front: "图形组成相似时，样式规律常考什么？",
    back: "常看遍历和加减同异。遍历是缺啥补啥；加减同异看相同位置线条的相加、相减、求同、求异。",
    tags: ["图推", "样式"],
  },
  {
    id: "graphic-pdf-005",
    category: "判断推理",
    subcategory: "空间类",
    front: "空间类图推主要包括哪些训练方向？",
    back: "包括空间重构、截面图、立体拼合、三视图等。做题时先确认可见面、相邻关系、相对关系和观察方向。",
    tags: ["空间", "图推"],
  },
  {
    id: "quantity-pdf-001",
    category: "数量关系",
    subcategory: "代入排除",
    front: "代入排除法适合哪些数量题？",
    back: "适合多位数、年龄、不定方程、余数、和差倍比、复杂方程等。先用尾数、奇偶、倍数排除，再代入好算项或最值项。",
    tags: ["数量", "方法"],
  },
  {
    id: "quantity-pdf-002",
    category: "数量关系",
    subcategory: "奇偶特性",
    front: "加减法中的奇偶口诀是什么？",
    back: "同奇同偶结果为偶，一奇一偶结果为奇。若两数之和或差为奇偶，另一种运算结果同奇偶，称为和差同性。",
    tags: ["数量", "奇偶"],
  },
  {
    id: "quantity-pdf-003",
    category: "数量关系",
    subcategory: "奇偶特性",
    front: "乘法中的奇偶口诀是什么？",
    back: "一个因数为偶则乘积为偶，全部因数为奇乘积才为奇。",
    tags: ["数量", "奇偶"],
  },
  {
    id: "quantity-pdf-004",
    category: "数量关系",
    subcategory: "倍数特性",
    front: "什么时候考虑倍数特性法？",
    back: "题干出现分数、百分数、比例、倍数、分组等表达，且对象必须是整数时，优先考虑倍数特性。",
    tags: ["数量", "倍数"],
  },
  {
    id: "quantity-pdf-005",
    category: "数量关系",
    subcategory: "整除判定",
    front: "常用整除判定有哪些？",
    back: "3 或 9 看各位数字和；5 看末位 0 或 5；4 或 25 看末两位；能用整除先限制选项。",
    tags: ["数量", "整除"],
  },
  {
    id: "verbal-pdf-001",
    category: "言语理解与表达",
    subcategory: "中心理解",
    front: "中心理解题的做题顺序是什么？",
    back: "先看提问方式，再读文段，最后比选项。优先寻找中心句，有中心句做同义替换，无中心句做全面概括。",
    tags: ["言语", "主旨"],
  },
  {
    id: "verbal-pdf-002",
    category: "言语理解与表达",
    subcategory: "中心理解",
    front: "中心理解题常见提问关键词有哪些？",
    back: "常见有“主要、旨在、重在、意在、想要说明、主旨、主题、观点、概括、态度、标题”等。",
    tags: ["言语", "提问方式"],
  },
  {
    id: "verbal-pdf-003",
    category: "言语理解与表达",
    subcategory: "关联词",
    front: "转折关系文段的重点在哪里？",
    back: "转折之后是重点。看到虽然但是、尽管可是、不过、然而、却、其实、事实上、实际上，重点看转折后内容。",
    tags: ["言语", "转折"],
  },
  {
    id: "verbal-pdf-004",
    category: "言语理解与表达",
    subcategory: "关联词",
    front: "因果关系文段的重点在哪里？",
    back: "结论是重点。看到所以、因此、因而、故而、于是、可见、看来、导致、致使、造成等，重点看结论句。",
    tags: ["言语", "因果"],
  },
  {
    id: "verbal-pdf-005",
    category: "言语理解与表达",
    subcategory: "略读信息",
    front: "片段阅读中哪些内容通常可以略读？",
    back: "例子、原因、背景、下定义后的解释说明通常服务于观点；定位中心时可略读，但细节题仍要回看。",
    tags: ["言语", "阅读"],
  },
  {
    id: "data-pdf-001",
    category: "资料分析",
    subcategory: "做题策略",
    front: "资料分析结构阅读的两步是什么？",
    back: "20-30 秒内不读具体数据，先圈时间和主体，再看材料结构关系，如总分、分总、并列分类等。",
    tags: ["资料", "阅读"],
  },
  {
    id: "data-pdf-002",
    category: "资料分析",
    subcategory: "审题",
    front: "资料分析审题的核心顺序是什么？",
    back: "圈时间，判断运算方式；判题型，抓占、均、倍等关键词；定主体，确认问的是谁。",
    tags: ["资料", "审题"],
  },
  {
    id: "data-pdf-003",
    category: "资料分析",
    subcategory: "速算策略",
    front: "资料分析速算为什么要重视选项？",
    back: "选项决定精算程度。能瞪则瞪，瞪不出来再动笔；选项差距大可截位估算，差距小再精算。",
    tags: ["资料", "速算"],
  },
  {
    id: "data-pdf-004",
    category: "资料分析",
    subcategory: "加法技巧",
    front: "精确求和或求差时尾数法怎么用？",
    back: "从尾部 1-2 位入手。选项末位不同看末一位；末位相同看末两位，用来快速锁定答案。",
    tags: ["资料", "加法"],
  },
  {
    id: "data-pdf-005",
    category: "资料分析",
    subcategory: "加法技巧",
    front: "高位叠加法适合什么情况？",
    back: "非精确求和或没有选项可参考时，从高位加起，先抓主要数量级，再补低位误差。",
    tags: ["资料", "加法"],
  },
  {
    id: "data-pdf-006",
    category: "资料分析",
    subcategory: "平均估算",
    front: "削峰填谷法如何求平均值？",
    back: "先选一个接近各数的基准值，再算偏离总和；平均值 = 基准值 + 偏离总和 / 项数。",
    tags: ["资料", "平均"],
  },
  {
    id: "data-pdf-007",
    category: "资料分析",
    subcategory: "减法技巧",
    front: "整数基准值法如何做减法？",
    back: "被减数 - 减数 = (被减数 - 基准值) + (基准值 - 减数)。选接近减数且好算的整数作基准。",
    tags: ["资料", "减法"],
  },
  {
    id: "data-pdf-008",
    category: "资料分析",
    subcategory: "乘法技巧",
    front: "小分互换法的核心是什么？",
    back: "把乘法中的常见小数或百分数转成分数，把多位乘法变成除法。比如乘 5、25、125 可转成除以 2、4、8 后放大。",
    tags: ["资料", "乘法"],
  },
  {
    id: "data-pdf-009",
    category: "资料分析",
    subcategory: "综合分析",
    front: "资料分析综合分析题先看哪些选项？",
    back: "可优先看前四题未出现过的答案，以及 C、D 项；但最终仍要回到材料验证，不能只靠经验。",
    tags: ["资料", "综合分析"],
  },
];

export const defaultMemoryCards: MemoryCard[] = threeColorMemoryCards as MemoryCard[];

export const toolboxCategories = [
  {
    id: "data",
    title: "资料分析",
    desc: "公式、速算、分数记忆、计算器和计时器",
  },
  {
    id: "graphics",
    title: "图形推理 / 空间想象",
    desc: "六面体、立体拼合、截面图、三视图训练",
  },
  {
    id: "cards",
    title: "行测记忆卡片",
    desc: "按资料分类形成可翻转、可复习、可导入的卡片库",
  },
] as const;
